# Generated by Django 5.0.1 on 2024-02-22 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('ca_name', models.CharField(default='', max_length=100)),
                ('ca_image', models.ImageField(default=None, upload_to='images')),
                ('ca_explanation', models.CharField(default='', max_length=1000)),
                ('ca_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('ca_created_date', models.DateTimeField(auto_now_add=True)),
                ('ca_modify_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='CategoryDetails',
            fields=[
                ('category_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('cad_name', models.CharField(default='', max_length=100)),
                ('cad_image', models.ImageField(default=None, upload_to='images')),
                ('cad_explanation', models.CharField(default='', max_length=1000)),
                ('cad_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('cad_created_date', models.DateTimeField(auto_now_add=True)),
                ('cad_modify_date', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CategoryDetails',
            },
        ),
    ]
