# Generated by Django 5.0.1 on 2024-02-29 03:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category_categorydetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('pay_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_type', models.PositiveIntegerField(default=1, help_text='1: Chi tiền, 2: Thu tiền, ...')),
                ('p_money', models.IntegerField(default=0)),
                ('p_explanation', models.CharField(default='', max_length=1000)),
                ('p_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('p_created_date', models.DateTimeField(auto_now_add=True)),
                ('p_modify_date', models.DateTimeField(auto_now=True)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('category_details_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.categorydetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Pay',
            },
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(default='', max_length=100)),
                ('u_image', models.ImageField(default=None, upload_to='images')),
                ('u_sdt', models.CharField(default='', max_length=20)),
                ('u_gender', models.PositiveIntegerField(default=1, help_text='1: Nam, 2: Nữ, ...')),
                ('u_birthday', models.DateTimeField(auto_now_add=True)),
                ('u_address', models.CharField(default='', max_length=200)),
                ('u_job', models.CharField(default='', max_length=100)),
                ('u_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('u_created_date', models.DateTimeField(auto_now_add=True)),
                ('u_modify_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserDetails',
            },
        ),
    ]
