# Generated by Django 5.0.1 on 2024-02-29 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_pay_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='ac_bank',
        ),
        migrations.RemoveField(
            model_name='account',
            name='ac_currency',
        ),
        migrations.RemoveField(
            model_name='user',
            name='number_coins',
        ),
    ]
