# Generated by Django 5.0.1 on 2024-02-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_categorydetails_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='pay',
            name='p_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
