# Generated by Django 5.0.1 on 2024-02-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pay_p_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pay',
            name='p_date',
            field=models.DateTimeField(),
        ),
    ]
