# Generated by Django 5.0.1 on 2024-02-29 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_pay_p_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorydetails',
            name='cad_type',
            field=models.PositiveIntegerField(default=1, help_text='1: Chi tiền, 2: Thu tiền, ...'),
        ),
    ]
