# Generated by Django 5.0.1 on 2024-03-09 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_helpinfomation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='helpinfomation',
            table='helpInfomation',
        ),
    ]
