# Generated by Django 5.0.1 on 2024-03-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_helpinfomation_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id_n',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
