# Generated by Django 5.0.1 on 2024-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_helpinfomation_helpinformation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpinformation',
            name='id_hvsi',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
