# Generated by Django 5.0.1 on 2024-03-09 08:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_helpinformation_id_hvsi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpinformation',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
