# Generated by Django 5.0.1 on 2024-03-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_helpinformation_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpinformation',
            name='user_id',
        ),
    ]
