# Generated by Django 5.0.1 on 2024-01-25 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_first_name', models.CharField(default='', max_length=75)),
                ('u_last_name', models.CharField(default='', max_length=75)),
                ('u_type', models.IntegerField(choices=[(1, 'User'), (2, 'Admin')], default=1)),
                ('u_email', models.CharField(default='', max_length=100)),
                ('u_mobile', models.CharField(default='', max_length=15)),
                ('u_mobile_code', models.CharField(default='', max_length=6)),
                ('u_password', models.CharField(default='', max_length=100)),
                ('u_auth_token', models.CharField(default='', max_length=100)),
                ('u_device_token', models.CharField(max_length=150)),
                ('u_reset_code', models.CharField(default='0000', max_length=6)),
                ('u_number_coins', models.IntegerField(default=0)),
                ('u_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')], default=1)),
                ('u_created_date', models.DateTimeField(auto_now_add=True)),
                ('u_modify_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('user_details_id', models.AutoField(primary_key=True, serialize=False)),
                ('ud_name', models.CharField(max_length=100)),
                ('ud_image', models.ImageField(upload_to='user_images/')),
                ('ud_birthday', models.DateTimeField(auto_now=True)),
                ('ud_gender', models.CharField(max_length=10)),
                ('ud_job', models.CharField(max_length=100)),
                ('ud_status', models.IntegerField(choices=[(1, 'Active'), (2, 'Deleted')])),
                ('ud_created_date', models.DateTimeField(auto_now_add=True)),
                ('ud_modify_date', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
