# Generated by Django 5.0.1 on 2024-02-29 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_account_ac_bank_remove_account_ac_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorydetails',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
