# Generated by Django 5.0.1 on 2024-03-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='ca_type',
            field=models.PositiveIntegerField(default=1, help_text='1: Chi tiền, 2: Thu tiền, ...'),
        ),
    ]
