# Generated by Django 5.0.1 on 2024-03-08 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_account_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='notification',
            fields=[
                ('id_n', models.AutoField(primary_key=True, serialize=False)),
                ('text_n', models.TextField()),
                ('read_status', models.IntegerField(default=1, help_text='1: active, 2: deleted')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
            },
        ),
    ]
