# Generated by Django 5.0.1 on 2024-03-11 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_category_ca_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='u_sdt',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='u_birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
