# Generated by Django 5.0.1 on 2024-03-09 07:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='helpInfomation',
            fields=[
                ('id_hvsi', models.AutoField(primary_key=True, serialize=False)),
                ('HDSD', models.TextField()),
                ('website', models.URLField()),
                ('followFB', models.URLField()),
                ('shareFB', models.URLField()),
                ('usageA', models.TextField()),
                ('PAP', models.TextField()),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
